### ISSUE TITLE
Under windows: OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by jonathon-love** [tonysimpson/nanomsg-python#47]
hi,

i installed nanomsg-python with `pip install nanomsg`, but when i try and import from it, i receive the following errors. my application works fine under OSX, and i'm only encountering this issue on windows.

from googling, i think the first line of the error might be diagnostic to someone who knows what it means.

<img width="958" alt="screen shot 2016-02-03 at 13 54 53" src="https://cloud.githubusercontent.com/assets/3240247/12771563/45677a4e-ca7e-11e5-8d66-ee985b2b3bad.png">

could someone shed some light on this?

with thanks

**Comment by jonathon-love** [comment]
ok, it looks like the nanomsg.dll is missing. i've gotten it to work by building nanomsg.dll and copying it to the `Scripts` folder of my virtualenv. poking around in the site-packages/nanomsg* directories, i can't find this dll anywhere, so perhaps it isn't shipped with the package at all?

this is all in python 3.5

**Comment by amiden** [comment]
you need build nanomsg.dll with CMAKE

**Comment by codypiersall** [comment]
You can find some binary wheels [on appveyor](https://ci.appveyor.com/project/codypiersall/nanomsg-python/build/1.0.27).  Just click on the right environment, then click "Artifacts".  These were made with the  1.0.0 tag of nanomsg.  PR #54 will make this part of this repository.
